import ClientWrapper from "@/components/ClientWrapper"; // Import the client component
import Header from "@/components/Header";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Define fonts here
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Export metadata (Server Component)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-blue-100 dark:bg-gray-900 text-gray-900 dark:text-gray-100`}
      >
        <ClientWrapper>
          {" "}
          {/* Client Component for client-side logic */}
          <Header />
          {children}
        </ClientWrapper>
      </body>
    </html>
  );
}
